#!/bin/bash
# Build the Handover Linux controller (Flutter) from a clean checkout.
#
#   tools/build-linux.sh [output dir]       default: dist/
#
# Inputs : HANDOVER_RENDEZVOUS_SERVER and HANDOVER_SERVER_KEY, from the environment or the git-ignored .env
#          (see .env.example); a release build refuses to start without them.
# Needs  : Rust per rust-toolchain.toml, Flutter 3.24.5, clang/libclang, cmake, ninja, pkg-config, GTK3 and the
#          libvpx/aom/opus/libyuv development packages (libyuv needs a libyuv.pc; on Arch create one pointing at
#          /usr/lib/libyuv.so). Bridge files are generated by tools/gen-bridge.sh when missing.
# Output : <out>/handover-linux-x64.tar.gz and <out>/SHA256SUMS. No service, no package scripts, nothing is installed.
# The result is scanned for vendor hosts; the build fails if any are found.
set -euo pipefail
cd "$(dirname "$0")/.."

# Reproducibility: build from a fixed absolute path. Native code (vendored OpenSSL, C sources) embeds absolute
# paths that no compiler flag can remap, so the checkout is bind-mounted at /mnt in a private mount namespace
# (no root needed). HANDOVER_REPRODUCIBLE=0 builds in place instead (the result then depends on where you build).
if [ -z "${HANDOVER_IN_NS:-}" ] && [ "${HANDOVER_REPRODUCIBLE:-1}" = 1 ]; then
  if unshare -rm true 2>/dev/null; then
    export HANDOVER_IN_NS=1 HANDOVER_SRC="$PWD"
    exec unshare -rm bash -c 'mount --bind "$HANDOVER_SRC" /mnt && cd /mnt && exec tools/build-linux.sh "$@"' _ "$@"
  fi
  echo "warning: user/mount namespaces are unavailable; building in place (not reproducible across directories)" >&2
fi
[ -z "${HANDOVER_SHOW_ROOT:-}" ] || { pwd; exit 0; }
OUT=${1:-dist}
export PATH=$HOME/.cargo/bin:$HOME/.local/share/mise/shims:$PATH
# Reproducibility: fixed build date from the commit time, source paths remapped.
export SOURCE_DATE_EPOCH=${SOURCE_DATE_EPOCH:-$(git log -1 --format=%ct)}
export RUSTFLAGS="${RUSTFLAGS:-} --remap-path-prefix=$HOME/.cargo=/cargo --remap-path-prefix=$HOME/.rustup=/rustup"
export CFLAGS="${CFLAGS:-} -ffile-prefix-map=$PWD=."
# Old bundled C++ (libwebm) does not include <cstdint>; newer GCC no longer provides it implicitly.
export CXXFLAGS="${CXXFLAGS:-} -include cstdint -ffile-prefix-map=$PWD=."

for t in cargo flutter cmake ninja pkg-config clang; do
  command -v "$t" >/dev/null || { echo "missing tool: $t" >&2; exit 2; }
done
pkg-config --exists libyuv || { echo "libyuv.pc not found (see the header of this script)" >&2; exit 2; }
FLUTTER_BIN=$(mise where flutter@3.24.5 2>/dev/null)/bin
[ -x "$FLUTTER_BIN/flutter" ] && export PATH=$FLUTTER_BIN:$PATH
flutter --version 2>/dev/null | head -1 | grep -q "3.24.5" || { echo "Flutter 3.24.5 is required" >&2; exit 2; }

if [ ! -f src/bridge_generated.rs ] || [ ! -f flutter/lib/generated_bridge.dart ]; then
  tools/gen-bridge.sh
fi

echo "== Rust library (release, --locked)"
cargo build --locked --release --features flutter,linux-pkg-config --lib
echo "== Flutter bundle (release, --enforce-lockfile)"
(cd flutter && flutter pub get --enforce-lockfile)
# The first build in a fresh tree can compile the plugins before Flutter has generated its headers
# (empty ephemeral/flutter_linux); the second run succeeds, so retry once.
(cd flutter && { flutter build linux --release || { echo "retrying the Flutter build once"; flutter build linux --release; }; })

BUNDLE=flutter/build/linux/x64/release/bundle
[ -x "$BUNDLE/handover" ] || { echo "bundle not produced: $BUNDLE/handover" >&2; exit 1; }

echo "== vendor-host scan"
HITS=0
for f in "$BUNDLE"/handover "$BUNDLE"/lib/librustdesk.so; do
  if strings -a "$f" | grep -aE 'rustdesk\.(com|cn)|rs-ny\.|rs-sg\.|rs-cn\.|stun\.l\.google|stun\.cloudflare|stun\.antisip|stun\.nextcloud|nip\.io|telegram\.org'; then
    HITS=1
  fi
done
[ "$HITS" = 0 ] || { echo "vendor hosts found in the build (listed above)" >&2; exit 1; }
echo "none found"

mkdir -p "$OUT"
tar -C "$(dirname "$BUNDLE")" --sort=name --mtime="@$SOURCE_DATE_EPOCH" --owner=0 --group=0 --numeric-owner -cf - bundle | gzip -n > "$OUT/handover-linux-x64.tar.gz"
(cd "$OUT" && sha256sum handover-linux-x64.tar.gz | tee SHA256SUMS)
