#!/bin/bash
# Regenerate third_party/ (vendored copies of every git-sourced dependency) from Cargo.lock and the matching
# source-replacement block in .cargo/config.toml. crates.io dependencies are NOT vendored; they stay pinned by
# the checksums in Cargo.lock.
#
#   tools/vendor-forks.sh            re-vendor exactly what Cargo.lock says
#
# To update a fork: change its rev in the manifest, `cargo update -p <name>`, run this script, review the diff of
# third_party/, commit. Vendored files are force-added because the vendored crates carry files .gitignore would
# otherwise drop, and Cargo checksums every file (a missing one breaks the build on a fresh clone).
set -euo pipefail
cd "$(dirname "$0")/.."
CFG=.cargo/config.toml
TMP=$(mktemp -d)
trap 'rm -rf "$TMP"' EXIT

# Vendor from the real upstream sources, not from the current third_party/.
cp "$CFG" "$TMP/config.toml.orig"
sed '/^# BEGIN vendored forks/,/^# END vendored forks/d' "$TMP/config.toml.orig" > "$CFG"
restore() { cp "$TMP/config.toml.orig" "$CFG"; }
trap 'restore; rm -rf "$TMP"' EXIT

cargo vendor --locked --versioned-dirs "$TMP/all" > "$TMP/vendor.config"

python3 - "$TMP" <<'PY'
import os, re, shutil, sys
tmp = sys.argv[1]
lock = open('Cargo.lock').read()
pkgs = re.findall(r'\[\[package\]\]\nname = "([^"]+)"\nversion = "([^"]+)"\nsource = "git\+', lock)
shutil.rmtree('third_party', ignore_errors=True)
os.makedirs('third_party')
for n, v in pkgs:
    shutil.copytree(f'{tmp}/all/{n}-{v}', f'third_party/{n}-{v}', symlinks=True)
blocks = [b.strip() for b in open(f'{tmp}/vendor.config').read().split('\n\n')]
out = ['# BEGIN vendored forks (generated by tools/vendor-forks.sh)',
       '# crates.io dependencies are not vendored: they stay pinned by Cargo.lock checksums.']
for b in blocks:
    if b.startswith('[source."git+'):
        out.append(b.replace('replace-with = "vendored-sources"', 'replace-with = "handover-vendored-forks"'))
out.append('[source.handover-vendored-forks]\ndirectory = "third_party"')
out.append('# END vendored forks')
base = open('.cargo/config.toml').read().rstrip('\n')
open('.cargo/config.toml', 'w').write(base + '\n\n' + '\n\n'.join(out) + '\n')
print(f'vendored {len(pkgs)} git packages')
PY
trap 'rm -rf "$TMP"' EXIT
git add -f third_party "$CFG"
echo "third_party/ and $CFG updated and staged; review with: git diff --cached --stat | tail"
